name: my test pipeline

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run bash script
        run: echo "hello"

      - name: run multi line script
        run: |
          ls -l
          ls /

      - name: use secret
        run: echo "the  secret is ${{ secrets.MY_SECRET }}"

      - name: say hi
        run: echo "hi"

      - name: say bye
        run: echo "bye"
